src/components/common/Card/Card.stories.tsx, src/components/common/Card/index.tsx, src/components/ui/card.tsx
카드 컴포넌트 구현했습니다. 다만 Card 컴포넌트가 CardContent, CardHeader .... 처럼 export 되는게 많아서 Card Container 컴포넌트 스타일만 수정하고 다른건 크게 건드리지 않았습니다...!
다음과 같이 사용할 수 있습니다!
```tsx
import Card from "@components/common/Card";
<Card.Container verticalPaddingSize={'large'}>
<Card.Content className={'p-0 text-regular-body font-semibold text-center'}>
텍스트를 입력하세요
</Card.Content>
</Card.Container>
```
아래가 ShadCN 에서 import 할 수 있는 Card관련 컴포넌트 목록입니다!
```tsx
<Card>
<CardHeader>
<CardTitle>Card Title</CardTitle>
<CardDescription>Card Description</CardDescription>
</CardHeader>
<CardContent>
<p>Card Content</p>
</CardContent>
<CardFooter>
<p>Card Footer</p>
</CardFooter>
</Card>
```
그리도 다음과 같은 형태로 re export 되고 있습니다!
```tsx
const Card = {
Container,
Header: CardHeader,
Content: CardContent,
Title: CardTitle,
Description: …
```
=> [#21] 카드 컴포넌트 작성 및 스토리북 작성

.storybook/preview-head.html, index.html, src/__test__/FontTest.stories.tsx, src/index.css
프리텐다드 폰트 적용하고 확인용 스토리북 작성 했습니다!
=> [#45] 프리텐다드 폰트 추가 및 스토리북 작성

.storybook/preview.ts, src/components/common/Badge/Badge.stories.tsx, src/components/common/Badge/index.tsx, src/components/common/Card/Card.stories.tsx, src/components/common/List/index.tsx, src/components/common/TextFieldV2/index.tsx, src/components/ui/badge.tsx
뱃지 컴포넌트 구현했습니다! 추가적으로 storybook 배경색 피그마랑 통일 시켰습니다!
아래처럼 사용할 수 있습니다!
```tsx
<Badge type="button" text="뱃지" size="meidum" onClick={}  />
```
인터페이스 정보 입니다!
```tsx
interface BadeWrapperProps extends Omit<HTMLAttributes<HTMLButtonElement>, 'type'> {
text: string;
type?: 'button' | 'display';
size?: 'medium' | 'small';
}
```
보시는 것처럼 text, type, size 라는 프로퍼티를 받고 이외에 버튼 태그에 사용되는 애트리뷰트를 받을 수 있게 했습니다!
추가적으로 리스트 스토리북에 뱃지도 교체했습니다!
=> [#24] 뱃지 컴포넌트 구현

src/components/common/TextField/index.tsx
1. x버튼 클릭 시 value값 안 지워지는 버그 해결했습니다 !
https://github.com/user-attachments/assets/9af9edd0-7163-4494-9e36-71d7c77eec0c
=> [#52] x버튼 클릭 시 value값 안 지워지는 버그 해결

index.html, package.json, pnpm-lock.yaml, public/firebase-sw.js, src/libs/firebase.ts, src/pages/Main.tsx, src/vite-env.d.ts
완전 push 알림 관련 기능을 구현한건 아니고 어느정도 뼈대를 만들어 뒀습니다!
=> [#134] FCM 환경 설정 및 기능 뼈대 구현

src/App.tsx, src/apis/user/getRegions.ts, src/components/register/RegionList.tsx, src/funnel/register/LocationFunnel.tsx, src/pages/ErrorPage.tsx, src/pages/RegisterPage.tsx
사용자 정보 등록 페이지의 위치 퍼널에서 위치 검색시 레이아웃이 깨지던 문제 해결했습니다!
- 부가적으로 에러 상태 관리 하도록 했고 서치 파라미터가 비어있으면 요청을 보내지 않도록 했습니다.
=> [# 139] 사용자 정보 등록 페이지에서 위치 등록시 레이아웃 깨지던 문제 해결

src/apis/user/registerUser.ts, src/pages/LoginRedirectPage.tsx, src/pages/RegisterPage.tsx
=> [# 148] 쿠키 만료 일자 설정 로직 현재 일자에서 더하도록 수정

src/apis/plantGuide/searchPlant.ts, src/components/common/Skeleton/ListSkeleton.tsx, src/components/ui/skeleton.tsx, src/constants/day.ts, src/mocks/handlers.ts, src/pages/LoginRedirectPage.tsx, src/pages/SearchPlantPage.tsx
=> [# 155] 식물 검색 페이지 로딩, 에러 UI 수정

src/components/searchPlant/SearchedPlantList.tsx, src/pages/SearchPlantPage.tsx, src/queries/useSearchPlant.ts
=> fix: reject, pending 폴백 수정 및 suspenseQuery 에서 query 로 수정

src/apis/user/getMyPageData.ts, src/apis/user/updateAlarmStatus.ts, src/apis/user/updateAlarmTime.ts, src/apis/user/updateNickname.ts, src/components/common/Header/index.tsx, src/components/profile/ModifyNickname.tsx, src/components/profile/MyProfile.tsx, src/components/profile/SetNotifications.tsx, src/mocks/handlers.ts, src/mocks/mockDatas/myPageData.ts, src/pages/AddPlantPage.tsx, src/pages/Profile.tsx, src/queries/keyStore.ts, src/queries/useGetMyPageData.ts, src/queries/useUpdateAlarmStatus.ts, src/queries/useUpdateAlarmTime.ts, src/queries/useUpdateNickname.ts, src/types/profile.ts
마이페이지 서버 연결 진행했습니다.
- 응답 모킹
- 낙관적 업데이트로 알림 상태 및 시간대 수정
=> [# 176] 마이페이지 서버 연결

src/apis/user/createDeviceToken.ts, src/apis/user/deleteDeviceToken.ts, src/hooks/useNotification.tsx, src/mocks/handlers.ts, src/pages/Main.tsx, src/pages/RegisterPage.tsx, src/providers/GlobalModalProvider.tsx, src/queries/keyStore.ts, src/queries/useCreateDeviceToken.ts, src/queries/useDeleteDeviceToken.ts, src/queries/useUpdateAlarmStatus.ts
=> [# 185] 푸쉬 알림 허용, 거절 기능 구현

src/components/common/Separator/index.tsx
`Separator` 컴포넌트 UI 수정했습니다.
- `Separator` 컴포넌트 `max-width` 적용
=> [# 196] 세퍼레이터 max width 적용

src/components/common/CenterBottomSheet/index.tsx
센터 파텀 시트 컴포넌트 UI 수정
- 헤더 위 세퍼레이터에 y 마진 10px 추가
- 헤더에 white-space-pre-wrap 추가
- 푸터 actions에 gap 12px 추가
=> [# 198] 센터 바텀 시트 컴포넌트 UI 수정

src/pages/AddPlantPage.tsx
식물 추가 페이지 상단 x 버튼 클릭시 뒤로가기가 아닌 메인페이지로 가도록 수정했습니다.
- AddPlantPage 컴포넌트의 Header 버튼이 goBack이 아닌 replace('/")를 실행하도록 변경
=> [# 204] 식물 추가 페이지 상단 x 버튼 클릭시 뒤로가기가 아닌 메인페이지로 가도록 수정

src/apis/myPlant/uploadMyPlantImage.ts, src/components/myPlantEdit/ImageInputWithList.tsx, src/components/myPlantEdit/MostRecentImage.tsx, src/libs/firebase.ts, src/mocks/handlers.ts, src/mocks/mockDatas/myPlantDetail.ts, src/pages/MyPlantEdit.tsx, src/queries/keyStore.ts, src/queries/useUploadMyPlantImage.ts
이미지 업로드 기능 구현
- 업로드 실패시 toast 표시
- 로딩 UI 구현
- 이미지는 1개씩 업로드로 제한
=> [# 215] 이미지 업로드 기능 구현

src/components/LoadingSpinner.tsx, src/components/addPlant/NotificationToggle.tsx, src/components/addPlant/NotificationToggleList.tsx, src/components/addPlant/PlantTypeTextField.tsx, src/components/common/CenterBottomSheet/index.tsx
식물 물주기, 비료주기 추가 바텀 시트 값 선택했는데도 추천값이 사용된다는 다이얼로그가 발생하던 문제 해결
- 바텀시트의 CTA 버튼이 onClose 함수를 호출하는게 아닌 setIsOpen(false)를 호출하도록 변경
=> [# 228] 식물 물주기, 비료주기 추가 바텀 시트 오류 수정

src/components/main/RegisterMyPlant.tsx
=> [# 246] whitespace pre wrap 적용한 후 스플릿 메서드 제거

src/components/main/MyPlantAlimCheck.tsx, src/utils/home/getRandomIllustrator.ts
=> [# 257] svg 이미지로 불러오던 방식 rollback

src/components/register/RegionList.tsx, src/funnel/register/LocationFunnel.tsx
=> [# 263] 주소 검색 결과 없을시 UI 수정 및 선택 UI 추가

src/apis/user/deleteDeviceToken.ts
=> [# 293] 디바이스 토큰 삭제 엔드포인트 수정

src/components/addPlant/함께하기시작한날.tsx, src/utils/date/prefixWithZero.ts
=> [# 298] 날짜에 0 프리픽스 추가

src/hooks/useNotification.tsx, src/pages/Main.tsx
=> [# 309] 웹에서의 알림 기능 제거

src/components/addPlant/NotificationToggle.tsx, src/components/addPlant/NotificationToggleList.tsx, src/components/addPlant/PlantLocationBadgeList.tsx, src/components/addPlant/마지막으로물준날.tsx, src/components/addPlant/마지막으로비료준날.tsx, src/components/addPlant/함께하기시작한날.tsx, src/components/common/CTAButton/index.tsx, src/components/common/SegmentControl/index.tsx, src/components/myPlant/DeleteConfirmation.tsx, src/components/myPlant/LocationInput.tsx, src/components/profile/ModifyNickname.tsx, src/components/profile/UseInformation.tsx, src/components/searchPlant/SearchedPlantList.tsx, src/funnel/register/CompleteFunnel.tsx, src/funnel/register/LocationFunnel.tsx, src/funnel/register/NicknameFunnel.tsx, src/funnel/register/NotificationTimeFunnel.tsx, src/hooks/useNotification.tsx, src/pages/AddPlantPage.tsx, src/pages/ErrorPage.tsx, src/pages/MyPlantEdit.tsx, src/pages/MyPlantFeedPage.tsx
=> [# 317] cta 버튼 인터페이스 추상화 수준 수정 및 적용

src/App.tsx, src/components/myPlantEdit/ImageInputWithList.tsx, src/constants/routes.tsx, src/hooks/useInternalRouter.ts
=> [# 326] 라우트 배열로 분리 후 타입 세이프 라우팅 구현

.github/workflows/install-build-test.yaml, package.json, pnpm-lock.yaml, src/__test__/AddPlantPage.test.tsx, src/__test__/helpers/wrapper.tsx, src/__test__/setup.ts, src/components/searchPlant/SearchedPlantList.tsx, src/pages/SearchPlantPage.tsx, vitest.config.ts
=> [# 328] 식물 등록 페이지 식물 종류 입력 로직 테스트 추가

src/components/myPlantDetail/PlantImageCarousel.tsx, src/mocks/mockDatas/myPlantDetail.ts
=> [# 330] 식물 사진 없는 경우 기본 이미지 노출

src/apis/myPlant/updateMyPlantAlarm.ts, src/pages/MyPlantDetail.tsx, src/queries/useUpdateMyPlantAlarm.ts
=> [# 334] 내 식물 알람 업데이트 API 변경 사항 반영

src/pages/AddPlantPage.tsx
식물 등록시 닉네임 필드 값이 비어져서 요청이 보내지던 문제 수정했습니다.
- 닉네임 입력 텍스트 필드에 이벤트 핸들러 등록되어있지 않던 문제 수정
=> fix: 식물 등록시 닉네임 필드 값이 비어져서 요청이 보내지던 문제 수정

src/apis/myPlant/updateMyPlantFeed.ts
- 즐겨찾기 실패하는 문제 수정
- 즐겨찾기 수정 요청에 요청 본문 추가
=> fix: 즐겨찾기 실패하는 문제 수정
