dnd-side-project/dnd-11th-8-frontend

package.json, pnpm-lock.yaml, src/hooks/useInternalRouter.ts
1.  internalrouter 훅 구현하기
1. react-router-dom 설치
---
close #6
=> internalrouter 훅 구현하기

.gitignore, src/App.tsx, src/components/auth/KakaoLogin.tsx
1. 카카오 소셜 로그인 구현 (토큰 받아오기)
1. App.tsx에 컴포넌트 호출한거 커밋하긴 했지만 나중에 삭제할 예정입니다 !
close #3
=> 카카오 소셜 로그인 구현 

src/App.tsx
=> chore: test

.storybook/preview.ts, package.json, pnpm-lock.yaml, vite.config.ts
storybook 배포 사이트가 제대로 동작하지 않는거 같아서... 원인을 찾아보다 vite pwa plugin 제거하고 잘 동작한다는 코멘트를 보고 제거해 봤습니다. 일단 로컬에서는 잘 동작하는데 배포하면 어떻게 될지 잘 모르겠긴 해요...!
vite pwa plugin이 제거되었습니다...! 아마 merge conflict가 생길 수 있을거 같아요!
=> feat: storybook 설정 추가 및 pwa 플러그인 제거

.github/workflows/install-build-test.yaml
=> fix: 리뷰어 PR 생성한 보인 확인하도록 수정

tailwind.config.js
테일윈드 폰트 사이즈 테마 추가 했습니다!
tailwindcss.config.js 파일 수정되었어요! 확인 부탁드립니다! 수정 하실거 있으면 수정해주세요...ㅠ 클래스 명을 잘 했는지 모르겠습니다...ㅎ
=> config: tailwind 폰트 사이즈 테마 추가

src/components/common/CTAButton/CTAButton.stories.tsx, src/components/common/CTAButton/index.tsx, tailwind.config.js
CTA 버튼 구현했습니다.
```tsx
<CTAButton text="등록하기" onClick={} color="disabled" />
```
와 같은 형식으로 사용할 수 있습니다.
tailwindCSS Config에 폰트 하나 빠져있던거 추가했습니다. `regular-body` 입니다!
=> [#20] CTA 버튼 구현

src/components/common/SegmentControl/SegmentControl.stories.tsx, src/components/common/SegmentControl/index.tsx
1. SegmentControl 컴포넌트 구현 완료 했습니다!
2. 스토리북으로도 구현 완료 했습니다 !
3. 사진에는 안나왔는데 흰색배경 아래에 shadow추가했습니다 ~
4. 쓰실 때는 아래와같이 사용하시면 됩니다 !
```
function App() {
const handleSegmentChange = (selectedSegment: { id: number; name: string }) => {
console.log('선택한 ID:', selectedSegment.id);
console.log('선택한 이름:', selectedSegment.name);
};
return (
<div>
<SegmentControl segments={segments} onSegmentChange={handleSegmentChange} />
</div>
);
}
```
=> [#27] SegmentControl 구현

src/components/common/SearchField/SearchField.stories.tsx, src/components/common/SearchField/index.tsx, src/components/common/TextField/index.tsx
1. 서치 필더 구현 완료
2. 서치 필더 스토리북 구현
=> [#23] 서치 필더 구현  

package.json, pnpm-lock.yaml, src/components/common/BottomSheet/BottomSheet.stories.tsx, src/components/common/BottomSheet/index.tsx, src/components/ui/drawer.tsx
바텀시트 컴포넌트 작성했습니다! 다음과 같이 사용할 수 있습니다!
```tsx
<Button onClick={() => setIsOpen(true)}>바텀시트 열기</Button>
<BottomSheet
isOpen={isOpen}
onClose={() => setIsOpen(false)}
title={'타이틀은\n두줄까지만 권장합니다'}
content={content}
actions={[
<CTAButton text={'등록하기'} color={'active'} onClick={() => setIsOpen(false)} />,
]}
/>
```
콘텐츠와 actions로 컴포넌트를 props로 받게 했습니다...!
=> [#22] 바텀시트 컴포넌트 작성

.env.development, src/apis/auth/appleLogin.ts, src/components/auth/AppleLogin.tsx, src/libs/baseAxios.ts, src/vite-env.d.ts
애플 로그인 미완성된 부분 채워넣었습니다!
추가적으로 env 파일 타입 시스템 추가, axios 인스턴스 export 작업 진행했습니다~~!
=> [#12] 애플 로그인 구현

.env.development, src/App.tsx, src/components/auth/AppleLogin.tsx, src/vite-env.d.ts
라우트 절대 경로로 변경하고, 애플 로그인 URI 변경 했습니다...!
=> fix: 애플 로그인 수정 및 라우트 추가

vercel.json
=> fix: 루트 주소가 아닌 경로로 접속시 404 에러 발생하는 문제 해결

src/App.tsx, src/components/guide/NoSearchPlant.tsx, src/components/guide/Search.tsx, src/components/guide/TopButton.tsx, src/components/guideDetail/TopButton.tsx, src/pages/Guide.tsx
가이드 페이지 ui 구현 했습니다 ~
https://github.com/user-attachments/assets/eec52dcf-a86e-42e2-8bff-257a412d4506
=> [#82] 가이드 페이지 ui 구현 

package.json, pnpm-lock.yaml, src/apis/myPlant/getMyPlantDetail.ts, src/components/addPlant/NotificationToggleList.tsx, src/components/myPlantDetail/MyPlantInfo.tsx, src/components/myPlantDetail/PlantInfo.tsx, src/hooks/useInternalRouter.ts, src/mocks/handlers.ts, src/mocks/mockDatas/myPlantDetail.ts, src/pages/MyPlantDetail.tsx, src/queries/keyStore.ts, src/queries/useGetMyPlantDetail.ts
내 식물 정보 페이지 기능 구현했습니다!
- React Query 구현 및 서스펜스 바운더리 적용
- 페이지 단위 서스펜스 바운더리 적용을 위한 `Async Boundary` 라이브러리 설치
- useInternalRouter 훅 내부 타입 추가 및 수정
https://github.com/user-attachments/assets/db43243b-c619-48c8-b74c-967b3adfd9d6
=> [#90] 내 식물 정보 페이지 기능 구현

.eslintrc.cjs, src/components/common/Header/index.tsx, src/components/common/HeightBox/index.tsx, src/components/common/ScrollPicker/index.tsx, src/components/common/TextField/index.tsx, src/components/register/RegisterFunnelTitle.tsx, src/funnel/register/CompleteFunnel.tsx, src/funnel/register/LocationFunnel.tsx, src/funnel/register/NicknameFunnel.tsx, src/funnel/register/NotificationTimeFunnel.tsx, src/hooks/useInternalRouter.ts, src/pages/RegisterPage.tsx, src/types/NewmericRange.ts
유저 정보 입력 UI 구현했습니다!
UI 개발이라 별다른 변경 사항 없습니다!
- switch case 문을 사용해 퍼널 단위 입력 페이지 개발
https://github.com/user-attachments/assets/2179d266-6c26-4b7d-bab4-26fb709407db
=> [# 98] 유저 정보 입력 UI 구현

src/components/common/SegmentControl/index.tsx, src/components/myPlant/BottomSheet.tsx, src/components/myPlant/LocationInput.tsx, src/components/myPlant/OptionsMenu.tsx, src/components/myPlant/PlusButton.tsx, src/pages/MyPlant.tsx
1. 전체 탭 추가
2. 전체라는 공간명은 삭제 및 수정 불가 
3. 플로팅 버튼에서 공간명 수정할때 패딩값 수정 
4. 레이아웃 적용
=> [#102] 내 식물 리스트 페이지 바뀐 내용 수정

src/components/guide/Search.tsx, src/components/guide/TopButton.tsx, src/pages/Guide.tsx
1. 레이아웃 적용
2. 뒤로가기 구현
3. 리스트 컴포넌트 클릭 시 상세 페이지로 이동
=> [#107] 가이드 페이지 레이아웃 적용

src/components/profile/ModifyNickname.tsx, src/components/profile/MyProfile.tsx, src/components/profile/SetNotifications.tsx, src/components/profile/UseInformation.tsx
1. 알림 클릭 시 알림 페이지(?)로 가기?? → 피그마 업데이트 아직 안됌
2. 내 식물 클릭 시 내 식물 페이지로 이동 ✔️
3. 로그아웃 클릭 시 바텀시트로 로그아웃 확인 메세지 보여주기 ✔️
4. 탈톼하기 클릭 기 바텀시트로 탈퇴 확인 메세지 보여주기 ✔️
5. 알람 시간대 다시 재설정하기 ✔️
---
---
=> [#112] 마이페이지 바뀐 내용 수정 

src/pages/MyPlantEdit.tsx
=> fix: eslint build 에러 수정

src/apis/myPlant/updateMyPlant.ts, src/components/addPlant/DateScrollPicker.tsx, src/components/addPlant/NotificationToggleList.tsx, src/components/addPlant/PlantLocationBadgeList.tsx, src/components/addPlant/SimpleDateScrollPicker.tsx, src/components/addPlant/마지막으로물준날.tsx, src/components/addPlant/마지막으로비료준날.tsx, src/components/addPlant/함께하기시작한날.tsx, src/components/myPlant/MyPlantList.tsx, src/components/myPlantEdit/MostRecentImage.tsx, src/mocks/handlers.ts, src/mocks/mockDatas/myPlantDetail.ts, src/pages/AddPlantPage.tsx, src/pages/MyPlantDetail.tsx, src/pages/MyPlantEdit.tsx, src/queries/keyStore.ts, src/queries/useUpdateMyPlant.ts, src/utils/int/parseOrUndefined.ts
내 식물 수정 페이지 기능 구현 했습니다~!
- 스크롤 피커 세부 구현 수정: type을 exact와 simple 값을 받아 그에 따른 UI 변경이 가능하도록 했습니다. (함수 시그니처랑 세부 구현 변경 예정)
https://github.com/user-attachments/assets/76ddf1de-c666-4c8b-b0eb-bae478b9acd9
=> [#123] 내 식물 수정 페이지 기능 구현

src/components/addPlant/PlantLocationBadgeList.tsx
=> [# 128] 내 식물 위치 등록시 위치 중복 체크

src/constants/addPlant.ts
마지막으로 물 준날 비료 준 날 값 API랑 동기화 시켰습니다~~!
=> [# 130] 마지막으로 물, 비료 준 날 값 1 ~ 6으로 변경

src/apis/auth/signIn.ts
code로 idToken 발급 받는 로직 추가했습니다!
=> [#135] 카카오 로그인 로그인 로직 수정

src/apis/auth/signIn.ts, src/utils/encode/formUrlEncoded.ts, src/vite-env.d.ts
=> [# 135] 카카오 로그인 credential 오류 해결

src/hooks/useToast.tsx, src/pages/Main.tsx, src/pages/RegisterPage.tsx
=> [# 141] FCM 알림 기능 수정 및 사용자 정보 등록 에러 관리 로직 수정

src/apis/user/registerUser.ts
=> [# 143] 사용자 정보 등록 API 헤더값 수정

src/apis/home/getHomeScreenData.ts, src/apis/weathers/getWeatherMessage.ts, src/components/main/BloomingWeather.tsx, src/components/main/MyPlant.tsx, src/components/main/Weather.tsx, src/constants/weatherMessageIcon.ts, src/mocks/handlers.ts, src/mocks/mockDatas/homeData.ts, src/mocks/mockDatas/weatherMessage.ts, src/pages/ErrorPage.tsx, src/pages/Main.tsx, src/pages/MyPlantEdit.tsx, src/pages/RegisterPage.tsx, src/providers/GlobalModalProvider.tsx, src/queries/keyStore.ts, src/queries/useGetHomeData.ts, src/queries/useGetWeatherMessage.ts, src/types/weathers.ts
=> [# 145] 메인 페이지 API 연동

src/pages/ErrorPage.tsx, src/pages/Main.tsx
=> [# 145] 에러 페이지 수정 및 메인 페이지 에러 표기 수정

src/apis/auth/signIn.ts, src/pages/LoginRedirectPage.tsx
=> [# 148] 쿠키 만료 일자 설정 로직 수정 및 로그인 리디렉션 페이지 로딩 스피너 수정

src/mocks/handlers.ts, src/pages/Main.tsx
=> [# 151] 메인페이지 register 조건 수정

src/libs/baseAxios.ts, src/mocks/mockDatas/randomSigninData.ts
=> [# 153] 로그인 직후 요청에 헤더 포함 안되는 문제 수정

src/apis/plantGuide/searchPlant.ts, src/mocks/handlers.ts
=> [# 153] 식물 검색 API 쿼리 키 변경

src/pages/RegisterPage.tsx
=> [# 158] 토큰 만료 기간 밀리세컨드에서 세컨드로 변경

src/components/main/MyPlant.tsx
=> [# 160] 메인페이지 인삿말 수정

src/apis/plantGuide/searchPlant.ts, src/components/searchPlant/SearchedPlantList.tsx, src/mocks/handlers.ts
=> [# 162] 식물 검색 API 메서드 수정 및 이미지 URL 수정

src/pages/SearchPlantPage.tsx
=> fix: debounce delay 값 수정

.eslintrc.cjs, src/apis/auth/refreshAccessToken.ts, src/components/register/RegionList.tsx, src/hooks/useToken.ts, src/mocks/handlers.ts, src/mocks/mockDatas/refreshAccessToken.ts, src/pages/LoginRedirectPage.tsx, src/pages/Main.tsx, src/pages/RegisterPage.tsx, src/pages/SearchPlantPage.tsx, src/queries/keyStore.ts, src/queries/useRefreshAccessToken.ts
=> [# 166] 리프레쉬 토큰을 이용한 액세스 토큰 재갱신 기능 구현

src/components/guide/Search.tsx, src/mocks/mockDatas/searchPlant.ts
=> [# 171] 식물 가이드 검색 페이지 API 연동

src/App.tsx, src/apis/myPlant/getMyAllPlant.ts, src/atoms/myPlant/filterQueryAtom.ts, src/components/common/SegmentControl/index.tsx, src/components/main/MyPlantAlimCheck.tsx, src/components/myPlant/FilterButton.tsx, src/components/myPlant/MyPlantList.tsx, src/components/myPlant/MyPlantSupplement.tsx, src/mocks/handlers.ts, src/mocks/mockDatas/allMyPlant.ts, src/pages/MyPlant.tsx, src/queries/keyStore.ts, src/queries/useAllMyPlant.ts, src/queries/useGetAllMyPlant.ts, src/types/MyPlant.ts
=> [# 175] 내 식물 페이지 서버 연결

src/apis/auth/logout.ts, src/components/profile/UseInformation.tsx, src/mocks/handlers.ts, src/pages/Profile.tsx, src/queries/keyStore.ts, src/queries/useLogout.ts
=> [# 179] 로그아웃 기능 개발

src/components/myPlant/BottomSheet.tsx, src/components/myPlant/PlusButton.tsx
=> [# 187] 내 식물 페이지 위치 삭제 기능 구현

src/components/addPlant/PlantLocationBadgeList.tsx, src/components/common/CenterBottomSheet/index.tsx, src/components/common/SegmentControl/index.tsx, src/components/myPlant/BottomSheet.tsx, src/components/myPlant/DeleteConfirmation.tsx, src/components/myPlant/LocationInput.tsx, src/components/myPlant/OptionsMenu.tsx, src/components/myPlant/PlusButton.tsx, src/components/profile/UseInformation.tsx, src/components/searchPlant/SearchedPlantList.tsx, src/components/ui/dialog.tsx, src/hooks/useNotification.tsx, src/pages/MyPlant.tsx
=> [# 189] 내 식물 페이지 위치 수정 삭제 기능 구현

src/apis/auth/leave.ts, src/components/profile/UseInformation.tsx, src/queries/keyStore.ts, src/queries/useLeave.ts
=> [#192] 탈퇴하기 기능 

src/__test__/utils/validation.test.ts, src/apis/myPlant/createMyPlant.ts, src/components/addPlant/DateScrollPicker.tsx, src/components/addPlant/NotificationToggle.tsx, src/components/addPlant/NotificationToggleList.tsx, src/components/addPlant/PlantLocationBadgeList.tsx, src/components/addPlant/PlantTypeTextField.tsx, src/components/addPlant/함께하기시작한날.tsx, src/hooks/useSyncPlantType.ts, src/pages/AddPlantPage.tsx, src/pages/MyPlantDetail.tsx, src/pages/MyPlantEdit.tsx, src/types/date.ts, src/types/form.ts, src/utils/form/setForm.ts, src/utils/validation/isFalsy.ts
=> [# 193] 식물 등록 페이지 400에러 수정

src/apis/auth/leave.ts, src/apis/auth/logout.ts
토큰 삭제 API 하나로 통합 했습니다!
- logout.ts 파일 requestRemoveDeviceToken 삭제 및 apis/user/deleteDeviceToken 으로 수정
- leaveUser.ts 파일의 디바이스 토큰 삭제 API 역시 위와 동일하게 삭제 및 수정
=> [# 202] 토큰 삭제 API 하나로 통합

src/components/myPlant/DeleteConfirmation.tsx, src/components/myPlant/PlusButton.tsx
내 식물 페이지 위치 삭제 모달에 취소 버튼 추가했습니다!
=> [# 199] 내 식물 페이지 위치 삭제 모달에 취소 버튼 추가

src/apis/home/getHomeScreenData.ts, src/mocks/handlers.ts
홈화면 데이터 응답 `imageUrl`과 같이 실제 응답에 없는 값을 제거했습니다.
- Plant[] 타입에서 Pick 타입으로 변경
=> [# 207] getHomeScreenData 응답 타입 스웨거 문서와 동기화

src/apis/home/getHomeScreenData.ts, src/components/main/MyPlantAlimCheck.tsx, src/mocks/mockDatas/allMyPlant.ts, src/types/MyPlant.ts
홈 화면 undefined UI 에러 수정했습니다.
- 응답 리스폰스 프로퍼티 오타 수정
- nickname 이 ""(공백 문자열) 일 경우 식물 타입을 닉네임 대신 표현하도록 수정
=> [# 212] 홈 화면 undefined UI 에러 수정

src/components/common/TextField/index.tsx, src/funnel/register/NicknameFunnel.tsx
유저 정보 닉네임 등록 에러 UI 구현
- 정규 표현식 사용해 한글, 영어만 입력 받도록 구현
- 10자리 넘어가지 않도록 구현
- 텍스트 필드 인터페이스 수정
=> [# 217] 유저 정보 중 닉네임 등록시 에러 UI 구현

src/components/myPlant/MyPlantList.tsx
=> [# 219] 뱃지 사이즈 수정

src/components/addPlant/NotificationToggle.tsx, src/components/addPlant/NotificationToggleList.tsx
주기 입력하지 않고 바텀시트를 닫을 시 추천 주기가 사용된다는 모달창이 열리도록 구현했습니다.
=> [# 222] 주기 입력 하지 않고 바텀시트 닫을 시 추천 주기가 사용된다는 모달 창 열리도록함

src/apis/auth/leave.ts, src/apis/user/deleteUser.ts, src/components/profile/UseInformation.tsx, src/queries/keyStore.ts, src/queries/useDeleteUser.ts, src/queries/useLeave.ts
회원 탈퇴 API 스웨거 문서 기반으로 수정했고, leave -> deleteUser로 함수 시그니쳐 수정했습니다
=> [# 230] 회원 탈퇴 API 엔드포인트 수정 및 관련 함수 리팩터링

public/.well-known/assetlinks.json
=> [# 234] 에셋 링크 추가

src/components/common/BottomSheet/index.tsx, tailwind.config.js
바텀 시트에 최대 너비 적용 안되어 있던 문제 수정했습니다.
=> [# 238] 바텀시트 화면 너비 넓을 경우 UI 수정

package.json, pnpm-lock.yaml, vite.config.ts
=> [# 240] svg, image 최적화 라이브러리 도입

src/App.tsx, src/components/profile/ModifyNickname.tsx, src/pages/AddPlantPage.tsx, src/pages/AlimDetail.tsx, src/pages/Guide.tsx, src/pages/GuideDetails.tsx, src/pages/Main.tsx, src/pages/MyPlant.tsx, src/pages/MyPlantDetail.tsx, src/pages/MyPlantEdit.tsx, src/pages/MyPlantFeedPage.tsx, src/pages/Profile.tsx, src/pages/RegisterPage.tsx, src/pages/개인정보처리방침페이지.tsx, src/pages/서비스이용약관페이지.tsx, src/utils/asyncBoundary/withDefaultAsyncBoundary.tsx
=> [# 242] 페이지 레이지 로딩 적용

index.html
=> [# 248] preconnect 옵션 추가

package.json, pnpm-lock.yaml, vite.config.ts
=> [# 250] 텍스트 압축 적용

vite.config.ts
=> [# 250] 메뉴얼 청킹 옵션 추가

vite.config.ts
=> [# 250] 청킹 옵션 롤백

src/components/LoadingSpinner.tsx
=> [# fix] 로딩 페이지 텍스트 추가

src/components/main/MyPlantAlimCheck.tsx, src/utils/home/getRandomIllustrator.ts
=> [# 256] svg 에서 img로 수정

src/pages/AddPlantPage.tsx
=> [# 261] 식물 등록 후 홈 페이지데 반영 안되던 문제 해결

src/apis/myPlant/deleteMyPlantFeed.ts
=> [# 265] 피드 삭제 API 명세 수정

public/sw.js
=> [# 267] 워크박스 임포트 제거

index.html
=> [# 267] 레지스터 경로 수정

package.json, pnpm-lock.yaml, src/components/LoadingSpinner.tsx, src/components/addPlant/NotificationToggleList.tsx, src/components/myPlant/FilterButton.tsx, src/components/myPlant/MyPlantList.tsx, src/components/myPlant/OptionsMenu.tsx, src/components/myPlant/PlusButton.tsx, src/components/myPlantDetail/MyPlantFeedImage.tsx, src/hooks/useHandleImage.ts, src/mocks/handlers.ts, src/pages/MyPlantFeedPage.tsx
=> [# 270] framer motion 사용한 애니메이션 추가

public/.well-known/assetlinks.json
=> [# 272] 에셋링크 확인 에러 수정

index.html, public/robots.txt, public/sitemap.xml
=> [# 274] seo 개선 작업 진행

src/pages/Main.tsx
=> [# 276] 모달 오픈 안되는 문제 수정

src/hooks/useNotification.tsx
=> [# 276] 푸쉬 알림 기능 롤백

src/pages/Main.tsx, src/types/react-native.d.ts
=> [# 282] 로그인시 액세스 토큰 RN 환경으로 전송하는 로직 추가

src/pages/Main.tsx
=> [# 284] 웹, RN 에서의 푸시 알림 동작 분기 추가

.gitignore, package.json, pnpm-lock.yaml, vite.config.ts
=> [# 286] sentry 플러그인 적용

src/apis/myPlant/updateMyPlantStatus.ts, src/components/main/AlimCheck.tsx, src/components/main/MyPlantAlimCheck.tsx, src/mocks/handlers.ts, src/queries/keyStore.ts, src/queries/useUpdateMyPlantStatus.ts
=> [feat] 내 식물 알림 API 호출 기능 구현

package.json, pnpm-lock.yaml, src/hooks/useHandleImage.ts, vite.config.ts
=> [refactor] 이미지 업로드시 압축 로직 추가

src/apis/auth/logout.ts
=> [# 293] 로그아웃 안되는 문제 수정

src/components/main/CarouselCurrentSlide.tsx, src/components/main/MyPlantAlimCheck.tsx, src/components/main/MyPlantCarouselItem.tsx, src/mocks/mockDatas/homeData.ts
=> [# 295] 일러스트 랜덤 적용 및 최적화 적용

src/apis/user/deleteUser.ts
=> [# 302] 회원 탈퇴 안되던 문제 수정

src/components/profile/ModifyNickname.tsx, src/funnel/register/NicknameFunnel.tsx, src/utils/validation/validateNickname.ts
=> [# 304] 닉네임 수정 페이지 유효성 검증 추가

src/apis/user/deleteUser.ts
=> [# fix] 회원 탈퇴 안되던 문제 수정

src/components/common/SegmentControl/index.tsx
=> [# 307] 세그먼트 새 위치 추가 기능 구현

src/libs/baseAxios.ts, src/main.tsx, src/routes/PrivateRoute.tsx, src/utils/cookie/setCookie.ts
=> [# 311] 액세스 토큰 리프레시 로직 axios 미들웨어로 처리

src/apis/myPlant/getMyAllPlant.ts, src/pages/MyPlant.tsx, src/queries/useGetAllMyPlant.ts
=> [# 313] 내 식물 페이지 필터링 로직 리액트 쿼리 select로 처리

src/main.tsx
=> [# 315] retry는 의도적으로 발생할 수 있도록 retry 되지 않도록 리액트 쿼리 기본 설정 수정

src/components/common/CTAButton/index.tsx
=> [# 317] ghost 배리언트 컬러 수정

src/components/myPlantEdit/ImageInputWithList.tsx, src/pages/Main.tsx
=> [# 320] 내 식물 편집 페이지 이미지 리스트 + 버튼 클릭시 피드 페이지로 이동 기능 구현

src/apis/myPlant/deleteMyPlant.ts, src/main.tsx, src/mocks/handlers.ts, src/pages/MyPlantEdit.tsx, src/queries/keyStore.ts, src/queries/useDeleteMyPlant.ts
=> [# 322] 내 식물 삭제 API 연동

src/apis/user/updateAlarmStatus.ts
=> [# 324] 유저 알림 설정 수정 API 엔드포인트 수정

src/App.tsx, src/hooks/useToken.ts, src/libs/baseAxios.ts
=> [# 332] 리프레쉬 토큰 유효하지 않을 경우에 대한 로직 추가
